# Config file for automatic testing at travis-ci.org

language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install: pip install -U tox-travis flake8

# Command to run tests, e.g. python setup.py test
script:
  - flake8 .
  - tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mdboom2
  password:
    secure: UX0nwEz6fhe5PwT4ptrCfLpfWWeqHYHXelQgUZnvpSvYmnaVOGlDsgAYIalezRatqOHUx1UP7zCvQ+IbULn2hMocRKfE7CMvaKHbXYUiSBdAB8H86YcVFXoIshL/nLMypoANsIKljE2bv5FF5E3ru9mOo2UjPp9kC1hgFNuLo9ZWHZzuarsC6CAGtD1BnSyQa7ove0NP3pMe23Fe41OSYXJTSMXNXj9d3PT4WfsMBOYYvEA7WH4Eax5JtZcAMFhSnkCN0wdanVdStRrdyOrgc12AgbbVFvpEIrteahcNOJC7BJDm86JI1kKo+PZ//wf3fi+lZAvrg3wVXlvaJQ8xqwOidGAMdMqFuo+L/3Xyn6whkcFU7tQsXBVsF4GoL8EiKoDRNZ1rJu1AJvhyyq6mBvp142l1xSQrDwzbuqAlSSJH9Z4mDneSLf+AUDFiSDwwW/oYbOwm8pEvZUFZdAKEt2Rdt6LVn5+Ao7KV8F5YSvfHbyr9MfLsuO6zzjUxxm+nw1gdLnE1vN94veahCHb4n+oBwviLmtzYTrA967vgC9PPChGxCgrPhCqbCIwe1Xa+ivYqFu8LsIW19Sg2dqp1P9NyXTCWM3NPSakt6QyMWw9qS7zAt4yGt/rKLM46P7Ad1t+UKR9EqX84KL+z9WzG1gkForTmZYxCo6b9YIlcuDw=
  on:
    tags: true
    repo: mozilla/glean_parser
    python: 3.7
